import { startLogin } from "@/const";
import { ExplorerPortrait } from "@/components/ExplorerPortrait";
import { useLocale } from "@/contexts/LocaleContext";

function TinySpark() { return <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none"><path d="M12 2.7c.7 5.5 2.5 7.3 8 8.1-5.5.8-7.3 2.6-8 8.2-.7-5.6-2.5-7.4-8-8.2 5.5-.8 7.3-2.6 8-8.1Z" fill="currentColor"/><circle cx="19" cy="4.7" r="1.4" fill="currentColor"/></svg>; }
function ArrowGlyph() { return <svg aria-hidden="true" viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg>; }
function OrbitLogo() { return <svg aria-hidden="true" width="23" height="23" viewBox="0 0 42 42" fill="none"><circle cx="21" cy="21" r="5" fill="currentColor"/><ellipse cx="21" cy="21" rx="17" ry="7" stroke="currentColor" strokeWidth="2.4"/><path d="M32.3 9.3 35 6.6M34.3 12.1h3.8" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round"/></svg>; }
function MetricGlyph({ kind }: { kind: "time" | "feedback" | "insight" }) { return <svg aria-hidden="true" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{kind === "time" ? <><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></> : kind === "feedback" ? <><path d="m5 19 12-12"/><path d="m15 4 1-2m2 5 2-1m-5 4 1 2"/><path d="M4 20h.01"/></> : <><rect x="4" y="4" width="16" height="16" rx="3"/><path d="M8 16v-4m4 4V8m4 8v-2"/></>}</svg>; }

function LanguageToggle() {
  const { locale, setLocale, t } = useLocale();
  return <button type="button" className="language-toggle" onClick={() => setLocale(locale === "en" ? "ar" : "en")} aria-label={t("common.language")}><span className="language-mark">A</span><span>{locale === "en" ? "العربية" : "English"}</span></button>;
}

function AdventureScene({ questLabel, questTitle, level, skill }: { questLabel: string; questTitle: string; level: string; skill: string }) {
  return <section className="adventure-preview" aria-hidden="true"><svg className="landing-scene-svg" viewBox="0 0 720 500" preserveAspectRatio="none"><defs><linearGradient id="sky" x1="0" x2="1" y1="0" y2="1"><stop stopColor="#d7d0fb"/><stop offset=".65" stopColor="#f1eaff"/><stop offset="1" stopColor="#d9f1ef"/></linearGradient><linearGradient id="hillA" x1="0" x2="1"><stop stopColor="#97d8c1"/><stop offset="1" stopColor="#62b193"/></linearGradient><linearGradient id="hillB" x1="0" x2="1"><stop stopColor="#65af92"/><stop offset="1" stopColor="#469378"/></linearGradient></defs><rect width="720" height="500" fill="url(#sky)"/><circle cx="577" cy="95" r="110" fill="none" stroke="rgba(255,255,255,.62)" strokeWidth="17"/><path d="M-50 475C91 254 214 289 389 504H-50Z" fill="url(#hillA)"/><path d="M252 507c159-177 297-200 529-67v67H252Z" fill="url(#hillB)"/><path d="M287 416c26-36 51-72 78-107" stroke="#fff5d8" strokeWidth="6" strokeDasharray="4 18" strokeLinecap="round"/></svg><div className="preview-card preview-card-top"><span className="scene-mini-orbit"><TinySpark /></span><span><small>{questLabel}</small><b>{questTitle}</b></span><strong>5</strong></div><div className="preview-card preview-card-bottom"><ExplorerPortrait avatarKey="starlight" size="sm" eager /><span><small>{level}</small><b>{skill}</b><em><i /></em></span></div><div className="landing-character"><ExplorerPortrait avatarKey="ember" size="lg" eager /></div></section>;
}

export default function LandingPage() {
  const { t } = useLocale();
  return <div className="landing-page"><header className="landing-header"><a className="brand" href="#top"><span className="brand-mark"><OrbitLogo /></span><span>{t("brand.name")}</span></a><LanguageToggle /></header><main id="top" className="landing-main"><section className="landing-copy"><p className="eyebrow"><TinySpark />{t("landing.eyebrow")}</p><h1>{t("landing.title")}</h1><p className="landing-description">{t("landing.description")}</p><button type="button" className="primary-button landing-cta" onClick={startLogin}><span>{t("landing.primaryCta")}</span><ArrowGlyph /></button><div className="safety-note"><span className="safety-seal">✓</span><span><b>{t("landing.safety")}</b>{t("landing.safetyDetail")}</span></div></section><AdventureScene questLabel={t("dashboard.dailyQuest")} questTitle={t("quests.dailyFive")} level={t("dashboard.level", { level: 4 })} skill={t("skills.countTo20")} /></main><section className="landing-features"><p><span className="feature-glyph"><MetricGlyph kind="time" /></span>{t("landing.featureOne")}</p><p><span className="feature-glyph"><MetricGlyph kind="feedback" /></span>{t("landing.featureTwo")}</p><p><span className="feature-glyph"><MetricGlyph kind="insight" /></span>{t("landing.featureThree")}</p></section></div>;
}
