import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { Backpack, BarChart3, Check, Sparkles } from "@/components/AdventureArt";
import { useState } from "react";

type RewardCategory = "outfit" | "accessory" | "backpack" | "effect" | "pet";

function AdminMutationStatus({ state }: { state: { isSuccess: boolean; isError: boolean } }) {
  const { t } = useLocale();
  if (state.isError) return <p className="form-error" role="alert">{t("admin.saveError")}</p>;
  if (state.isSuccess) return <p className="admin-success"><Check size={14} />{t("admin.changesSaved")}</p>;
  return null;
}

export function AdminPanel({ curriculum }: { curriculum: any }) {
  const { t, number } = useLocale();
  const content = trpc.admin.content.useQuery();
  const { data: analytics } = trpc.admin.analytics.useQuery();
  const refresh = () => { content.refetch(); };
  const seed = trpc.admin.seedStarterContent.useMutation({ onSuccess: refresh });
  const saveWorld = trpc.admin.saveWorld.useMutation({ onSuccess: refresh });
  const saveSkill = trpc.admin.saveSkill.useMutation({ onSuccess: refresh });
  const saveTemplate = trpc.admin.saveQuestionTemplate.useMutation({ onSuccess: refresh });
  const saveQuest = trpc.admin.saveQuest.useMutation({ onSuccess: refresh });
  const saveReward = trpc.admin.saveReward.useMutation({ onSuccess: refresh });
  const [world, setWorld] = useState({ key: "", order: 1, nameKey: "", descriptionKey: "", accent: "sky", iconKey: "stars", isPublished: true });
  const [skill, setSkill] = useState({ key: "", worldKey: "number-valley", order: 1, nameKey: "", generatorKey: "count", isPublished: true });
  const [template, setTemplate] = useState({ key: "", skillKey: "count-to-20", kind: "count", difficulty: 1, isEnabled: true });
  const [quest, setQuest] = useState({ key: "", titleKey: "", target: 5, rewardXp: 25, rewardCoins: 10, isDaily: true, isEnabled: true });
  const [reward, setReward] = useState<{ key: string; titleKey: string; category: RewardCategory; costCoins: number; assetKey: string; isPublished: boolean }>({ key: "", titleKey: "", category: "effect", costCoins: 10, assetKey: "", isPublished: true });
  const items = content.data;
  const inputNumber = (value: string) => Number(value);

  return <main className="app-main admin-page"><section className="parent-heading"><div><p className="eyebrow"><Backpack size={15} />{t("admin.title")}</p><h1>{t("admin.contentStudio")}</h1><p>{t("admin.manageDetail")}</p></div></section>
    <section className="admin-grid"><article className="admin-summary-card"><span className="recommendation-star"><Sparkles size={22} /></span><p>{t("admin.curriculum")}</p><h2>{number(curriculum?.worlds?.length ?? 0)} {t("admin.worlds")}</h2><div className="admin-counts"><span>{number(curriculum?.skills?.length ?? 0)} {t("admin.skills")}</span><span>{number(curriculum?.lessons?.length ?? 0)} {t("admin.lessons")}</span></div><button className="primary-button" type="button" onClick={() => seed.mutate()} disabled={seed.isPending}><span>{seed.isPending ? t("common.loading") : t("admin.seed")}</span><Sparkles size={17} /></button></article><article className="admin-list-card"><div className="section-title"><div><p>{t("admin.analytics")}</p><h2>{t("admin.productHealth")}</h2></div><BarChart3 size={20} /></div><div className="admin-counts admin-metrics"><span>{number(analytics?.activeChildren ?? 0)} {t("admin.children")}</span><span>{number(analytics?.accuracy ?? 0)}% {t("parent.accuracy")}</span><span>{number(analytics?.attempts ?? 0)} {t("parent.questions")}</span></div></article></section>
    {content.isLoading ? <div className="lesson-loading"><Sparkles size={25} /><p>{t("common.loading")}</p></div> : content.isError ? <div className="empty-state"><p>{t("admin.saveError")}</p><button type="button" className="secondary-button" onClick={() => content.refetch()}>{t("common.retry")}</button></div> : <section className="admin-grid">
      <article className="admin-list-card"><h2>{t("admin.worldEditor")}</h2><select value="" onChange={event => { const item = items?.worlds.find((row: any) => row.key === event.target.value); if (item) setWorld(item); }}><option value="">{t("admin.selectWorld")}</option>{items?.worlds.map((item: any) => <option key={item.key} value={item.key}>{item.key}</option>)}</select><form className="profile-form" onSubmit={event => { event.preventDefault(); saveWorld.mutate(world); }}><label><span>{t("admin.key")}</span><input required value={world.key} onChange={event => setWorld({ ...world, key: event.target.value })} /></label><div className="form-row"><label><span>{t("admin.order")}</span><input type="number" min="1" value={world.order} onChange={event => setWorld({ ...world, order: inputNumber(event.target.value) })} /></label><label><span>{t("admin.published")}</span><input type="checkbox" checked={world.isPublished} onChange={event => setWorld({ ...world, isPublished: event.target.checked })} /></label></div><label><span>{t("admin.nameKey")}</span><input required value={world.nameKey} onChange={event => setWorld({ ...world, nameKey: event.target.value })} /></label><label><span>{t("admin.descriptionKey")}</span><input required value={world.descriptionKey} onChange={event => setWorld({ ...world, descriptionKey: event.target.value })} /></label><button className="secondary-button" disabled={saveWorld.isPending}><span>{t("admin.saveWorld")}</span><Check size={16} /></button><AdminMutationStatus state={saveWorld} /></form></article>
      <article className="admin-list-card"><h2>{t("admin.skillEditor")}</h2><select value="" onChange={event => { const item = items?.skills.find((row: any) => row.key === event.target.value); if (item) setSkill(item); }}><option value="">{t("admin.selectSkill")}</option>{items?.skills.map((item: any) => <option key={item.key} value={item.key}>{item.key}</option>)}</select><form className="profile-form" onSubmit={event => { event.preventDefault(); saveSkill.mutate(skill); }}><label><span>{t("admin.key")}</span><input required value={skill.key} onChange={event => setSkill({ ...skill, key: event.target.value })} /></label><label><span>{t("admin.worldEditor")}</span><select value={skill.worldKey} onChange={event => setSkill({ ...skill, worldKey: event.target.value })}>{items?.worlds.map((item: any) => <option key={item.key} value={item.key}>{item.key}</option>)}</select></label><div className="form-row"><label><span>{t("admin.order")}</span><input type="number" min="1" value={skill.order} onChange={event => setSkill({ ...skill, order: inputNumber(event.target.value) })} /></label><label><span>{t("admin.published")}</span><input type="checkbox" checked={skill.isPublished} onChange={event => setSkill({ ...skill, isPublished: event.target.checked })} /></label></div><label><span>{t("admin.nameKey")}</span><input required value={skill.nameKey} onChange={event => setSkill({ ...skill, nameKey: event.target.value })} /></label><label><span>{t("admin.generator")}</span><input required value={skill.generatorKey} onChange={event => setSkill({ ...skill, generatorKey: event.target.value })} /></label><button className="secondary-button" disabled={saveSkill.isPending}><span>{t("admin.saveSkill")}</span><Check size={16} /></button><AdminMutationStatus state={saveSkill} /></form></article>
      <article className="admin-list-card"><h2>{t("admin.templateEditor")}</h2><select value="" onChange={event => { const item = items?.questionTemplates.find((row: any) => row.key === event.target.value); if (item) setTemplate(item); }}><option value="">{t("admin.selectTemplate")}</option>{items?.questionTemplates.map((item: any) => <option key={item.key} value={item.key}>{item.key}</option>)}</select><form className="profile-form" onSubmit={event => { event.preventDefault(); saveTemplate.mutate(template); }}><label><span>{t("admin.key")}</span><input required value={template.key} onChange={event => setTemplate({ ...template, key: event.target.value })} /></label><label><span>{t("admin.skillEditor")}</span><select value={template.skillKey} onChange={event => setTemplate({ ...template, skillKey: event.target.value })}>{items?.skills.map((item: any) => <option key={item.key} value={item.key}>{item.key}</option>)}</select></label><div className="form-row"><label><span>{t("admin.kind")}</span><input required value={template.kind} onChange={event => setTemplate({ ...template, kind: event.target.value })} /></label><label><span>{t("admin.difficulty")}</span><input type="number" min="1" max="5" value={template.difficulty} onChange={event => setTemplate({ ...template, difficulty: inputNumber(event.target.value) })} /></label></div><label><span>{t("admin.enabled")}</span><input type="checkbox" checked={template.isEnabled} onChange={event => setTemplate({ ...template, isEnabled: event.target.checked })} /></label><button className="secondary-button" disabled={saveTemplate.isPending}><span>{t("admin.saveTemplate")}</span><Check size={16} /></button><AdminMutationStatus state={saveTemplate} /></form></article>
      <article className="admin-list-card"><h2>{t("admin.questEditor")}</h2><select value="" onChange={event => { const item = items?.quests.find((row: any) => row.key === event.target.value); if (item) setQuest(item); }}><option value="">{t("admin.selectQuest")}</option>{items?.quests.map((item: any) => <option key={item.key} value={item.key}>{item.key}</option>)}</select><form className="profile-form" onSubmit={event => { event.preventDefault(); saveQuest.mutate(quest); }}><label><span>{t("admin.key")}</span><input required value={quest.key} onChange={event => setQuest({ ...quest, key: event.target.value })} /></label><label><span>{t("admin.nameKey")}</span><input required value={quest.titleKey} onChange={event => setQuest({ ...quest, titleKey: event.target.value })} /></label><div className="form-row"><label><span>{t("admin.target")}</span><input type="number" min="1" value={quest.target} onChange={event => setQuest({ ...quest, target: inputNumber(event.target.value) })} /></label><label><span>{t("admin.daily")}</span><input type="checkbox" checked={quest.isDaily} onChange={event => setQuest({ ...quest, isDaily: event.target.checked })} /></label></div><div className="form-row"><label><span>{t("admin.rewardXp")}</span><input type="number" min="0" value={quest.rewardXp} onChange={event => setQuest({ ...quest, rewardXp: inputNumber(event.target.value) })} /></label><label><span>{t("admin.rewardCoins")}</span><input type="number" min="0" value={quest.rewardCoins} onChange={event => setQuest({ ...quest, rewardCoins: inputNumber(event.target.value) })} /></label></div><label><span>{t("admin.enabled")}</span><input type="checkbox" checked={quest.isEnabled} onChange={event => setQuest({ ...quest, isEnabled: event.target.checked })} /></label><button className="secondary-button" disabled={saveQuest.isPending}><span>{t("admin.saveQuest")}</span><Check size={16} /></button><AdminMutationStatus state={saveQuest} /></form></article>
      <article className="admin-list-card"><h2>{t("admin.rewardEditor")}</h2><select value="" onChange={event => { const item = items?.rewards.find((row: any) => row.key === event.target.value); if (item) setReward(item); }}><option value="">{t("admin.selectReward")}</option>{items?.rewards.map((item: any) => <option key={item.key} value={item.key}>{item.key}</option>)}</select><form className="profile-form" onSubmit={event => { event.preventDefault(); saveReward.mutate(reward); }}><label><span>{t("admin.key")}</span><input required value={reward.key} onChange={event => setReward({ ...reward, key: event.target.value })} /></label><label><span>{t("admin.nameKey")}</span><input required value={reward.titleKey} onChange={event => setReward({ ...reward, titleKey: event.target.value })} /></label><label><span>{t("admin.category")}</span><select value={reward.category} onChange={event => setReward({ ...reward, category: event.target.value as RewardCategory })}>{(["outfit", "accessory", "backpack", "effect", "pet"] as RewardCategory[]).map(category => <option key={category} value={category}>{category}</option>)}</select></label><div className="form-row"><label><span>{t("admin.cost")}</span><input type="number" min="0" value={reward.costCoins} onChange={event => setReward({ ...reward, costCoins: inputNumber(event.target.value) })} /></label><label><span>{t("admin.published")}</span><input type="checkbox" checked={reward.isPublished} onChange={event => setReward({ ...reward, isPublished: event.target.checked })} /></label></div><label><span>{t("admin.assetKey")}</span><input required value={reward.assetKey} onChange={event => setReward({ ...reward, assetKey: event.target.value })} /></label><button className="secondary-button" disabled={saveReward.isPending}><span>{t("admin.saveReward")}</span><Check size={16} /></button><AdminMutationStatus state={saveReward} /></form></article>
    </section>}</main>;
}
